/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation("org.wiremock:wiremock:3.0.3")

    // JSON handling
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.2")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.17.2")
    implementation("com.fasterxml.jackson.core:jackson-core:2.17.2")

    // JSON Patch & Merge Patch
    implementation("com.github.java-json-tools:json-patch:1.13")

    // Logging
    implementation("ch.qos.logback:logback-classic:1.5.13")

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    implementation("com.squareup.okhttp3:okhttp:5.1.0")
    testImplementation("uk.org.webcompere:system-stubs-jupiter:2.1.8")
    testImplementation(kotlin("test"))
    testImplementation("io.mockk:mockk:1.14.7")

    // Testcontainers for integration tests
    testImplementation("org.testcontainers:testcontainers:1.19.3")
    testImplementation("org.testcontainers:junit-jupiter:1.19.3")
    testImplementation("org.testcontainers:localstack:1.19.3")

    testRuntimeOnly("ch.qos.logback:logback-classic:1.5.+")
    testRuntimeOnly("org.slf4j:jul-to-slf4j:2.0.+")

    // Ktor (upgrade to 3.3.3)
    val ktorVersion = "3.3.3"
    implementation("io.ktor:ktor-server-core-jvm:$ktorVersion")
    implementation("io.ktor:ktor-server-netty-jvm:$ktorVersion")
    implementation("io.ktor:ktor-server-websockets-jvm:$ktorVersion")
    implementation("io.ktor:ktor-server-cors-jvm:$ktorVersion")
    implementation("io.ktor:ktor-server-content-negotiation-jvm:$ktorVersion")
    implementation("io.ktor:ktor-client-core-jvm:$ktorVersion")
    implementation("io.ktor:ktor-client-java:$ktorVersion")
    implementation("io.ktor:ktor-serialization-jackson-jvm:$ktorVersion")
    testImplementation("io.ktor:ktor-server-test-host-jvm:$ktorVersion")

    // DB migrations
    implementation("org.flywaydb:flyway-core:10.16.0")

    implementation("software.amazon.awssdk:dynamodb:2.27.18")
    implementation("software.amazon.awssdk:auth:2.27.18")

    // .env file support
    implementation("io.github.cdimascio:dotenv-kotlin:6.4.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application { mainClass.set("se.strawberry.app.MainKt") }


kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

// Use default test task; no separate unit/integration separation is needed.
tasks.named<Test>("test") {
    jvmArgs("-XX:+EnableDynamicAgentLoading")
    jvmArgs("-Xshare:off")
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// Ensure :app:check runs the default tests
tasks.named("check") {
    dependsOn(tasks.named("test"))
}
